spring:
  application:
    name: auth-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/jwt_security
    username: ${SPRING_DATASOURCE_SECURITY_USER}
    password: ${SPRING_DATASOURCE_SECURITY_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}