spring:
  application:
    name: business-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/cmsapi
    username: ${SPRING_DATASOURCE_CMSAPI_USER}
    password: ${SPRING_DATASOURCE_CMSAPI_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

security:
  aws:
    bucketName: ${AWS_BUCKET_NAME}
    bucketFolderName: ${AWS_BUCKET_FOLDER_NAME}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
