version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - cmsapi

  config-service:
    container_name: config-service
    image: config-service
    env_file:
      - .env
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    depends_on:
      - mysql
    networks:
      - cmsapi

  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8761:8761"
    depends_on:
      - mysql
      - config-service
    networks:
      - cmsapi

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8765:8765"
    depends_on:
      - mysql
      - config-service
      - discovery-service
    networks:
      - cmsapi

  business-service:
    container_name: business-service
    image: business-service
    build:
      context: ./business-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8764:8764"
    depends_on:
      - mysql
      - config-service
      - discovery-service
    networks:
      - cmsapi

  auth-service:
    container_name: auth-service
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8763:8763"
    depends_on:
      - mysql
      - config-service
      - discovery-service
      - business-service
    networks:
      - cmsapi


networks:
  cmsapi:
    driver: bridge