version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword
      MYSQL_DATABASE: cmsapi
      MYSQL_USER: admin
      MYSQL_PASSWORD: SecretPassword
    ports:
      - "3306:3306"
    networks:
      - promo


  liquibase:
    stdin_open: true
    image: liquibase
    build: ./liquibase
    environment:
      DATABASE_NAME: cmsapi
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: SecretPassword
      LOG_LEVEL: warning
      DATABASE_CONNECTION_ATTEMPTS: 10
    depends_on:
      - mysql
    volumes:
      - ./liquibase/changelog:/liquibase/changelog:ro,delegated
    networks:
      - promo


networks:
  promo: