version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: SecretPassword
    ports:
      - "3306:3306"
    networks:
      - promo


networks:
  promo: