name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  fetch-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: ./gradlew test

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Code Analysis with Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
      - name: Post-Analysis
        if: ${{ always() }}
        run: echo 'Generated Analysis Result'

